### ISSUE TITLE
Can not build with V3.1.4 with scss plugin

### ISSUE THREAD

**Issue by anthony0030** [jaredpalmer/razzle#1339]
### Current Behavior
I can not build the app

### Expected behavior

I can build the app

### Additional context
```
yarn run v1.22.4
$ razzle build
Creating an optimized production build...
Compiling client...
Failed to compile.

./src/assets/scss/styles.sass
TypeError: this[MODULE_TYPE] is not a function
    at runMicrotasks (<anonymous>)
 @ ./src/client/ClientApp.jsx 6:0-33
 @ ./src/client/index.jsx

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Razzle           | 3.1.4
| Razzle Plugins   | razzle-plugin-bundle-analyzer: 1.2.0, razzle-plugin-compression: 1.0.0, razzle-plugin-disable-sourcemaps: 1.0.6, razzle-plugin-scss: 3.1.4, razzle-plugin-serviceworker: 1.0.3
| Node             | v14.4.0
| Browser          | Chrome  83.0.4103.116 (Official Build) (64-bit)
| npm/Yarn         | 1.22.4
| Operating System | OSX 10.15.5
| TypeScript       | N/A
| React            | 16.13.1

**Comment by fivethreeo** [comment]
Can you try using just razzle-plugin-scss?

**Comment by fivethreeo** [comment]
Oh, Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.

**Comment by fivethreeo** [comment]
I test node 14 in ci now, cannot reproduce. But will keep this open :)

**Comment by fivethreeo** [comment]
You can try doing yarn why on razzle and razzle-plugin-scss dependencies to see if you have conflicting packages and add razzle's version of the dependency to resolutions in your package.json if you find any conflicts.

**Comment by anthony0030** [comment]
I fixed it by:
1) Adding all the dependencies from razzle and the razzle SCSS plugin
2) Removing them one by one till it breaks, finding the one that broke it, then removing the rest,

It was a conflict with @storybook/react@^5.3.19 version of mini-css-extract-plugin "^0.7.0"
version 0.9.0 builds with no problem.

what would you suggest? asking storybook to bump that dep?

**Comment by fivethreeo** [comment]
There will always be conflicts like this I think. So better to document how this can happen and how to resolve it. Maybe add some scripts to do this. Does anything like this already exist?

**Comment by fivethreeo** [comment]
The recommended approach seems like using peerDependencies in related packages. So any package related to razzle using any package included in razzle core/utils as dependencies should have that as a peerDependency. Then devs will get conflict warnings and can resolve it by using resolutions in their projects package.json

**Comment by anthony0030** [comment]
Makes sense, did I not get a warning because they are ```dependencies``` and not  ```peerDependencies``` or because they are the same major version ```0.X.X```?

**Comment by fivethreeo** [comment]
Because they were dependencies, and not peerDependencies so we got two instances of the same version in this case. Probably some shared globals that got mixed up.

**Comment by anthony0030** [comment]
Version ```3.1.5``` fixed this problem :) Thank you for your hard work, it is much appreciated!
